export const out = `<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" creator="Groundspeak Pocket Query" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd" xmlns="http://www.topografix.com/GPX/1/0">
  <name>Kosice</name>
  <desc>Geocache file generated by Groundspeak</desc>
  <author>Groundspeak</author>
  <email>contact@groundspeak.com</email>
  <time>2020-02-06T08:04:42.8912929Z</time>
  <keywords>cache, geocache, groundspeak</keywords>
  <bounds minlat="48.45535" minlon="20.852833" maxlat="48.99415" maxlon="21.658167" />
  <wpt lat="48.722217" lon="21.25555">
    <time>2020-01-01T00:00:00</time>
    <name>GC8HDCZ</name>
    <desc>0101 || 2020 by Someone, Unknown Cache (4/4)</desc>
    <url>http://www.geocaching.com/seek/cache_details.aspx?guid=74efebcf-f703-4346-bcab-d2e470039c61</url>
    <urlname>0101 || 2020</urlname>
    <sym>Geocache</sym>
    <type>Geocache|Unknown Cache</type>
    <groundspeak:cache id="7496390" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
      <groundspeak:name>0101 || 2020</groundspeak:name>
      <groundspeak:placed_by>Someone</groundspeak:placed_by>
      <groundspeak:owner id="6780112">Someone</groundspeak:owner>
      <groundspeak:type>Unknown Cache</groundspeak:type>
      <groundspeak:container>Small</groundspeak:container>
      <groundspeak:attributes>
        <groundspeak:attribute id="6" inc="0">Recommended for kids</groundspeak:attribute>
        <groundspeak:attribute id="40" inc="1">Stealth required</groundspeak:attribute>
        <groundspeak:attribute id="64" inc="1">Tree Climbing</groundspeak:attribute>
        <groundspeak:attribute id="13" inc="1">Available at all times</groundspeak:attribute>
        <groundspeak:attribute id="26" inc="1">Public transportation</groundspeak:attribute>
        <groundspeak:attribute id="25" inc="1">Parking available</groundspeak:attribute>
        <groundspeak:attribute id="1" inc="1">Dogs</groundspeak:attribute>
      </groundspeak:attributes>
      <groundspeak:difficulty>4</groundspeak:difficulty>
      <groundspeak:terrain>4</groundspeak:terrain>
      <groundspeak:country>Slovakia</groundspeak:country>
      <groundspeak:state>Košický kraj</groundspeak:state>
      <groundspeak:short_description html="True"></groundspeak:short_description>
      <groundspeak:long_description html="True">0101 || 2020Additional Waypoints

FN8HDCZ - Final Location
N/S __ ° __ . ___ W/E ___ ° __ . ___
0101 || 2020 FINAL</groundspeak:long_description>
      <groundspeak:encoded_hints></groundspeak:encoded_hints>
      <groundspeak:logs>
        <groundspeak:log id="903899907">
          <groundspeak:date>2020-01-18T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="9136543">Cacher01</groundspeak:finder>
          <groundspeak:text encoded="False">V ramci "rannej" rozcvicky som sa na bajku vybral aj k tejto novorocnej mysterke. Kukal som na nu ako puk, no napokon som poziadal o usmernenie a tak som sa po nom predsa len mohol vybrat to ocekovat do terenu.
Myslim, ze som dobre spravil, ze som sa sem vybral v sobotu, cez tyzden musi byt odlov (aspon pre nas, co mame radi sukromie pri odlove :-)) dost obtiazny. :-)
Kazdopadne stromcek zdolany, pekna schovka, ako je u ownera zvykom, potesila a tak teda dakujem za kes a posielam FP!</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="902122911">
          <groundspeak:date>2020-01-06T02:39:31Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="2658137">Cacher02</groundspeak:finder>
          <groundspeak:text encoded="False">18:37 [FTF]
Sedim si tak doma ked pipne nova mysterka. Mysterky mam rada, no vidim ze D4 T4, tak to bude asi nieco zlozite, navyse ten teren..tomu nedavam velku sancu. Pozeram na to zadanie dobru polhodinu, stahujem astroprogramceky aaaa NIC :/ Tak som to vzdala. Potom mi pise LuckaPali, ze jeeeej nova mysterka a tiez skusa v programceku nieco vyzistit. Tak tomu davam druhu sancu a opat na to pozeram a opat nic...pisem Lucke svoje nezistenia a zrazu tu ma osvietilo, tam ma osvietilo a uz len jej pisem ze to asi mam. Este kontrola checkerom a uz sa dohadujeme na odlove. Rebrik kamsi zmizol, tak len dufam, ze to nebude vysoko. 
Na mieste uz spolocne s LuckaPali sme to nasli rychlo... Pripojili sa aj Cacher03, lebo bez nich by sme tam nevyliezli, takze velke dakujem. 

Keska paradna veru a zadanie pre mna netradicne, zasluzi FB. 
IN/OUT: SWGcko
Takze teda este raz dakujem za paradnu kesku a aj super lustenie, to sa mi tiez pacilo.</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="902153678">
          <groundspeak:date>2020-01-05T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="23763045">Cacher03</groundspeak:finder>
          <groundspeak:text encoded="False">Spolocne {FTF} vdaka Cacher01 a Cacher02. 
Hned ako sme zistili, ze vysla nova zaujimava mysterka, skusili sme sa venovat lusteniu, nadialku konzultovali s Cacher01, ktora po chvili oznamila, ze na to prisla a aj checker odsuhlasil. Stretli sme sa na mieste, kde sme ale skonstatovali, ze odlov je nad nase sily. Nasledoval telefonat Cacher02, ktori bez vahania dorazili a kesku sikovne odlovili. 
Keska ma velmi pekne prevedenie, owner si dal skutocne zalezat. Dakujeme, +FP, TFTC :)</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="902138158">
          <groundspeak:date>2020-01-05T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="19933548">Cacher04</groundspeak:finder>
          <groundspeak:text encoded="False">{FTF} 5.1.2020, 18,37 hod.
Kludne si oddychujeme doma na gauci a zrazu telefon od geokolegov,  ze ide sa na novu mysterku. Ako sa hovori, ze sme prisli ako slepe kura k zrnu, tak tu to bolo to iste. Dakujeme Cacher02 a Cacher03 za pekny odlov a ownerovi za zalozenie krasnej kesky,   ktora si zasluzi FB ;-)</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="902057153">
          <groundspeak:date>2020-01-05T20:00:00Z</groundspeak:date>
          <groundspeak:type>Write note</groundspeak:type>
          <groundspeak:finder id="6780112">Cacher05</groundspeak:finder>
          <groundspeak:text encoded="False">In:
1 Swg na vymenu
Ceruzka a LB nie su na vymenu :-)
Vela stastia a nespadnite!</groundspeak:text>
        </groundspeak:log>
      </groundspeak:logs>
      <groundspeak:travelbugs />
    </groundspeak:cache>
  </wpt>
  <wpt lat="48.722817" lon="21.256783">
    <time>2019-06-04T00:00:00</time>
    <name>GC891J7</name>
    <desc>Immaculata  (Neposkvrnena) by Somebody, Virtual Cache (1/1)</desc>
    <url>http://www.geocaching.com/seek/cache_details.aspx?guid=8ad0ff46-f99e-4adc-bdfe-d21234c0dbd8</url>
    <urlname>Immaculata  (Neposkvrnena)</urlname>
    <sym>Geocache</sym>
    <type>Geocache|Virtual Cache</type>
    <groundspeak:cache id="7246693" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
      <groundspeak:name>Immaculata  (Neposkvrnena)</groundspeak:name>
      <groundspeak:placed_by>Somebody</groundspeak:placed_by>
      <groundspeak:owner id="8158338">Somebody</groundspeak:owner>
      <groundspeak:type>Virtual Cache</groundspeak:type>
      <groundspeak:container>Virtual</groundspeak:container>
      <groundspeak:attributes>
        <groundspeak:attribute id="32" inc="1">Bicycles</groundspeak:attribute>
        <groundspeak:attribute id="15" inc="1">Available during winter</groundspeak:attribute>
        <groundspeak:attribute id="13" inc="1">Available at all times</groundspeak:attribute>
        <groundspeak:attribute id="63" inc="1">Tourist Friendly</groundspeak:attribute>
        <groundspeak:attribute id="24" inc="1">Wheelchair accessible</groundspeak:attribute>
        <groundspeak:attribute id="6" inc="1">Recommended for kids</groundspeak:attribute>
        <groundspeak:attribute id="41" inc="1">Stroller accessible</groundspeak:attribute>
        <groundspeak:attribute id="1" inc="1">Dogs</groundspeak:attribute>
      </groundspeak:attributes>
      <groundspeak:difficulty>1</groundspeak:difficulty>
      <groundspeak:terrain>1</groundspeak:terrain>
      <groundspeak:country>Slovakia</groundspeak:country>
      <groundspeak:state>Košický kraj</groundspeak:state>
      <groundspeak:short_description html="True"></groundspeak:short_description>
      <groundspeak:long_description html="True">SK


V rokoch 1709 - 1710 bol v Kosiciach mor. Trvalo viac ako rok, kym mor skoncil.
Ti, co prezili, sa z vdaky poskladali na novy morovy stlp na nevhodnom mieste
stareho vojenskeho popraviska. Tento cin bol iniciovany zo strany postoveho
spravcu Viktorina Flachenfelda. Kym bol polozeny zakladny kamen, presli dva
roky. Stavbu bolo treba totiz zabezpecit nielen financnymi zbierkami, ale aj
najdenim vhodneho a skuseneho architekta. Stal sa nim kosicky stavitel Tomas
Tornyosi. Na samotne sochy bol lepsi odbornik sochar Simon Grimming, ktory s
architektom uzko spolupracoval. Reliefy s alegoriou Moru, Vojny a Hladu z
pozlateneho medeneho plechu, ktore boli umiestnene v spodnej casti susosia,
vytvoril zlatnik Juraj Immerwohl.


Vrchol susosia - Immaculatu predstavujuci Pannu Mariu, polozili 3. oktobra 1723
do vysky 14 metrov. Panna Maria ma symbolizovat vernost, lasku a dobrotu a mesto
ma chranit pred biedou a utrpenim. Ta ma nad hlavou veniec s dvanastimi
hviezdami. Okrem nej bolo susosie tvorene nizsie postavenymi sv. Jozefom, sv.
Sebastianom a sv.Ladislavom. Vsetky sochy mali plne tvary, rozviate rucha a na
stlpe je plno mracikov v tvare roznych kriviek a "kudrliniek", z ktorych bolo
jasne, ze ide o barokovy styl. Zaujimavostou je, ze v susosi sa ukryva aj socha
Svateho Valentina, svatca vsetkych zalubenych.


EN


In 1709 - 1710 there was a plague in Kosice. It took more than a year for the
plague to end. Survivors put themselves on a new plague pillar in an awkward
place of the old military execution. This action was initiated by the postal
administrator Viktorin Flachenfeld. Two years passed before the foundation stone
was laid. It was necessary to ensure the construction not only by financial
collections, but also by finding a suitable and experienced architect. It was
builder Tomas Tornyosi from Kosice. The sculptor Simon Grimming, who worked
closely with the architect, was better at the sculptures themselves. Reliefs
with the allegory of plague, war and hunger of gilded copper plate, which were
placed in the lower part of the sculpture, created by goldsmith Juraj Immerwohl. 
The top of the sculpture - Immaculata representing the Virgin Mary - was laid on
October 3, 1723, to a height of 14 meters. Our Lady is meant to symbolize
loyalty, love and goodness, and to protect the city from poverty and suffering.
She has a wreath of twelve stars over her head. In addition, the sculptural
group consisted of the lower-ranked St. Joseph, st. Sebastian and St.Ladislav.
All the statues were full-bodied, unfolded, and pillars were filled with clouds
in the form of various curves and "curls", which made it clear that it was a
Baroque style. It is interesting that there is also a statue of St. Valentine,
the saint of all loved ones.


SK:

Podmienka pre zalogovanie:

Najdi studnu,sadni si a vyfot seba alebo gps tak aby v zabere bola studna i
Immaculata (v mimoriadnych pripadoch beriem i obr.2 z reliefom)


EN:

Logging condition:

Find a well, sit down and take a picture of yourself or gps so that the well and
Immaculata (in extraordinary cases I also take Fig.2 with relief)



Virtual Rewards 2.0 - 2019/2020

This Virtual Cache is part of a limited release of Virtuals created between June
4, 2019 and June 4, 2020. Only 4,000 cache owners were given the opportunity to
hide a Virtual Cache. Learn more about Virtual Rewards 2.0 on the Geocaching
Blog</groundspeak:long_description>
      <groundspeak:encoded_hints>najdi studnu/find well</groundspeak:encoded_hints>
      <groundspeak:logs>
        <groundspeak:log id="905887574">
          <groundspeak:date>2020-01-30T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="26758447">Cacher01</groundspeak:finder>
          <groundspeak:text encoded="False">Spolu s kamaratom sme sa vybrali do Kosic na pivnu turistiku ktora je tu riadne fajna :-)
popri tom sme odlovili aj nejake kesky. Pocasie bolo fajn postupne ako pribudali pivka pribudali aj kesky :D s niektorymi sme sa potrapili viac s niektorymi vobec a niektore sme dokonca aj zle vyratali ale celkovo sme sa tu citili velmi dobre a urcite sa este vratime odlovit resty  ktore nam ostali. po tomto vikende si myslim ze sa k nasej geokeserskej partii prida aj kamarat ktoreho to riadne chytili. Dakujeme vsetkym ownerom za zalozenie a spravu kesiek a samozrejme aj za usmiatejsie Kosice</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="905695953">
          <groundspeak:date>2020-01-30T03:30:39Z</groundspeak:date>
          <groundspeak:type>Write note</groundspeak:type>
          <groundspeak:finder id="5269456">Cacher02</groundspeak:finder>
          <groundspeak:text encoded="False">dik za cache!</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="906300380">
          <groundspeak:date>2020-01-29T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="12136883">Cacher03</groundspeak:finder>
          <groundspeak:text encoded="False">Od autobusovej stanice sme sli rovno sem, aby sme sa tu odfotili. Miesto zname, ved uz sme tu nedaleko aj kesku lovili v minulosti. Dakujeme za usmiateho smajlika na nasej mape a pekny listing. TFTC</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="905625982">
          <groundspeak:date>2020-01-28T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="8017810">Cacher04</groundspeak:finder>
          <groundspeak:text encoded="False">28. januara 2020 1526
Uz som tu bol odkedy vznikla tato keska, ale vobec som nerozmyslal nad keskami. Vtedy som si povedal, ze dokelu.. mohol som ju bez problemov odlovit. Dnes ale v tento zasnezeny den prisla moznost ist do Kosic, ked som vecer isiel do divadla na Saru, a tesne predtym som sa z dialky odfotil s Immaculatou aj so studnou. Dakujem za ukazanie aj za informacie, ako katolikovi a dejepisarovi je mi to blizke.
Cesta naspat bola zaujimava po tych cestach :) TFTC</groundspeak:text>
        </groundspeak:log>
        <groundspeak:log id="905601542">
          <groundspeak:date>2020-01-28T20:00:00Z</groundspeak:date>
          <groundspeak:type>Found it</groundspeak:type>
          <groundspeak:finder id="13984305">Cacher05</groundspeak:finder>
          <groundspeak:text encoded="False">Dnes sa podarilo z Masiarskej ulice nostalgicky prejst popri prvej zmrzlinarni u Jusufiho, a nasledne pripomenut si tuto 300rocnu historiu, kratkou prechadzkou po meste. Vdaka za kesku</groundspeak:text>
        </groundspeak:log>
      </groundspeak:logs>
      <groundspeak:travelbugs />
    </groundspeak:cache>
  </wpt>
  </gpx>`;